// src/app/components/Nav/Nav.tsx
"use client";

import Link from "next/link";
import styled from "styled-components";
import { TitleContainer } from "../Container/TitleContainer";

const Nav = () => {
  return (
    <Section>
      <TitleContainer>
        <h1>다른 주제 더 보기</h1>
      </TitleContainer>
      <Container>
        <ul>
          <li>
            <Link href="/posts/programming">프로그래밍</Link>
          </li>
          <li>
            <Link href="/posts/movie">영화</Link>
          </li>
          <li>
            <Link href="/posts/etc">ETC</Link>
          </li>
        </ul>
      </Container>
    </Section>
  );
};

export default Nav;

const Section = styled.section`
  padding: 1.5rem 0 4rem 0;
`;

const Container = styled.nav`
  ul {
    display: flex;
    flex-direction: column;
    gap: 0;
    li {
      border: 0;
      border-bottom: 1px solid ${({ theme }) => theme.grayColor};
      border-radius: 0;
      font-size: 3rem;
      font-weight: 200;
      margin: 0;
      a {
        display: block;
        width: 100%;
        height: 100%;
        padding: 2rem 3rem;
      }
      &:first-child {
        border-top: 1px solid ${({ theme }) => theme.grayColor};
      }
      &:hover {
        a {
          cursor: pointer;
          color: white;
          background-color: ${({ theme }) => theme.hlColor_dark};
        }
      }
    }
  }
`;

// src/lib/components/Nav/Nav.svelte
<section class="max-w-[1200px] mx-auto px-[2.4rem] sm:px-[4.8rem] py-[4.8rem]">
	<h2 class="text-[3.2rem] font-bold text-basic mb-[2.4rem]">다른 주제 더 보기</h2>
	<nav>
		<ul class="flex flex-wrap gap-[1.2rem]">
			<li>
				<a class="block px-[2rem] py-[1rem] text-[1.4rem] font-medium text-[#666] border border-[#e5e5e5] rounded-[8px] no-underline hover:bg-hl hover:text-white hover:border-hl transition-all duration-200" href="/posts/programming">프로그래밍</a>
			</li>
			<li>
				<a class="block px-[2rem] py-[1rem] text-[1.4rem] font-medium text-[#666] border border-[#e5e5e5] rounded-[8px] no-underline hover:bg-hl hover:text-white hover:border-hl transition-all duration-200" href="/posts/movie">영화</a>
			</li>
			<li>
				<a class="block px-[2rem] py-[1rem] text-[1.4rem] font-medium text-[#666] border border-[#e5e5e5] rounded-[8px] no-underline hover:bg-hl hover:text-white hover:border-hl transition-all duration-200" href="/posts/etc">ETC</a>
			</li>
		</ul>
	</nav>
</section>
