// src/lib/components/Nav/Nav.svelte
<section class="mx-auto px-[3rem] sm:px-[3rem] py-[4.8rem]">
  <h2 class="text-[3.2rem] font-bold text-basic mb-[2.4rem]">콘텐츠</h2>
  <nav>
    <ul class="flex flex-col">
      <li class="border-b border-border">
        <a
          class="flex items-center justify-between py-[1.6rem] text-[3rem] font-medium text-basic no-underline hover:text-hl transition-colors duration-200"
          href="/posts/programming"
        >
          프로그래밍
        </a>
      </li>
      <li class="border-b border-border">
        <a
          class="flex items-center justify-between py-[1.6rem] text-[3rem] font-medium text-basic no-underline hover:text-hl transition-colors duration-200"
          href="/posts/movie"
        >
          영화
        </a>
      </li>
      <li class="border-b border-border">
        <a
          class="flex items-center justify-between py-[1.6rem] text-[3rem] font-medium text-basic no-underline hover:text-hl transition-colors duration-200"
          href="/posts/etc"
        >
          ETC
        </a>
      </li>
    </ul>
  </nav>
</section>

// src/components/Nav.tsx
export function Nav() {
	return (
		<section className="mx-auto px-[3rem] py-[4.8rem] sm:px-[3rem]">
			<h2 className="mb-[2.4rem] text-[3.2rem] font-bold text-basic">콘텐츠</h2>
			<nav aria-label="콘텐츠 카테고리">
				<ul className="flex flex-col">
					<li className="border-b border-border">
						<a className="flex items-center justify-between py-[1.6rem] text-[3rem] font-medium text-basic no-underline transition-colors duration-200 hover:text-hl" href="/posts/programming">
							프로그래밍
						</a>
					</li>
					<li className="border-b border-border">
						<a className="flex items-center justify-between py-[1.6rem] text-[3rem] font-medium text-basic no-underline transition-colors duration-200 hover:text-hl" href="/posts/movie">
							영화
						</a>
					</li>
					<li className="border-b border-border">
						<a className="flex items-center justify-between py-[1.6rem] text-[3rem] font-medium text-basic no-underline transition-colors duration-200 hover:text-hl" href="/posts/etc">
							ETC
						</a>
					</li>
				</ul>
			</nav>
		</section>
	);
}
