// src/app/components/Quotation/Quotation.tsx
"use client";

import { ReactNode } from "react";
import styled from "styled-components";

interface QuotationProps {
  type: "speak" | "think";
  children: ReactNode;
}
const Quotation = ({ children, type }: QuotationProps) => {
  return (
    <Container>
      <blockquote className="block-quotation">
        <span className="quotes">{type === "speak" ? `“` : `‘`}</span>
        {children}
        <span className="quotes">{type === "speak" ? `”` : `’`}</span>
      </blockquote>
    </Container>
  );
};

export default Quotation;

const Container = styled.div`
  @font-face {
    font-family: "NotoSerifKR";
    src: url("https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_two@1.0/NotoSerifKR.woff")
      format("woff");
    font-weight: normal;
    font-style: normal;
  }
  display: flex;
  justify-content: center;
  align-items: center;
  padding: 10rem 0 12rem;

  blockquote.block-quotation {
    margin: 0;
    padding: 0;
    background-color: unset;
    font-size: 2.8rem;
    font-family: "NotoSerifKR ", serif;
    font-style: italic;
    color: ${({ theme }) => theme.basicColor};
    span.quotes {
      font-family: "Times New Roman", Times, serif;
      color: ${({ theme }) => theme.grayColor_dark};
      font-style: italic;
    }
    &:after {
      display: none;
    }
  }
`;

// src/lib/components/Quotation/Quotation.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		type: 'speak' | 'think';
		children: Snippet;
	}
	let { type, children }: Props = $props();
</script>

<div class="flex justify-center items-center py-40 pb-48">
	<blockquote class="m-0 p-0 bg-transparent text-[2.8rem] italic text-basic" style="font-family: 'NotoSerifKR', serif;">
		<span class="text-gray-dark italic" style="font-family: 'Times New Roman', Times, serif;">{type === 'speak' ? '"' : "'"}</span>
		{@render children()}
		<span class="text-gray-dark italic" style="font-family: 'Times New Roman', Times, serif;">{type === 'speak' ? '"' : "'"}</span>
	</blockquote>
</div>
