// src/components/Quotation.tsx
import type { ReactNode } from 'react';

interface QuotationProps {
	type?: 'speak' | 'think';
	children: ReactNode;
}

export function Quotation({ type = 'speak', children }: QuotationProps) {
	return (
		<blockquote className="m-0 inline bg-transparent px-0 py-[1.2rem] text-[1.8rem] italic leading-[1.7] text-basic">
			<span className="not-italic">{type === 'speak' ? '“' : '‘'}</span>
			<em>{children}</em>
			<span className="not-italic">{type === 'speak' ? '”' : '’'}</span>
		</blockquote>
	);
}

// src/lib/components/Quotation/Quotation.svelte
<script lang="ts">
	import type { Snippet } from 'svelte';

	interface Props {
		type: 'speak' | 'think';
		children: Snippet;
	}
	let { type, children }: Props = $props();
</script>

<blockquote class="m-0 py-[1.2rem] px-0 bg-transparent text-[1.8rem] leading-[1.7] text-basic italic inline">
	<span class="not-italic">{type === 'speak' ? '\u201C' : '\u2018'}</span><em>{@render children()}</em><span class="not-italic">{type === 'speak' ? '\u201D' : '\u2019'}</span>
</blockquote>
